<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<title>固定表格测试</title>
<%@ include file="/jsp/taglibs.jsp" %>
<%@ include file="/jsp/meta.jsp" %>
<%@ include file="/jsp/bootstrap-top.jsp" %>
<script type="text/javascript" src="../tool/jquery/jquery.fixedtable.js"></script>
<link href="${ctx}/tool/bootstrap3/css/bootstrap-table.min.css" rel="stylesheet">
  <script type="text/javascript">
    $(document).ready(function() {
      var w=0;
      $("td:contains('（')").each(function(){
        var w_=parseFloat($(this).width());
        if(w_>w){w=w_}
      });
      $("td:contains('（')").each(function(){
        $(this).html(this.innerText+'<span style="visibility:hidden;">'+this.innerText+'</span>');
      });
      var options = {
        fixColumnColor: '#f2f2f2',
        fixColumnNumber: 3,
        width: 500,
        height: 300
      };
      $("#TableFreeze").fixedTable(options);
    })
  </script>
  <style>
    table,tr,td{
      border-collapse:collapse;
      letter-spacing:normal;
    }
    td{
      height:26px;border:1px solid #999;white-space: nowrap;
    }
  </style>
</head>
<body>

<table id="TableFreeze">
  <tr class="dstdeader"><td colspan="4" style="letter-spacing: 12px;" id="dataitem">数据项</td><td class="noReportOrgList">上次汇总保存的数据</td><td class="noReportOrgList">本次查询汇总结果</td><td class="noReportOrgList">本机构录入的数据</td><td class="noReportOrgList">北京市</td><td class="noReportOrgList">河北省</td><td class="noReportOrgList">内蒙</td><td class="noReportOrgList">黑龙江</td><td class="noReportOrgList">吉林省</td><td class="noReportOrgList">辽宁省</td><td class="noReportOrgList">天津市</td></tr>
  <tr><td rowspan="3" colspan="1" nowrap="nowrap">水果</td><td rowspan="1" colspan="1" nowrap="nowrap">南方水果</td><td rowspan="1" colspan="1" nowrap="nowrap">夏季水果</td><td rowspan="1" colspan="1" nowrap="nowrap">香蕉（千克）</td><td nowrap="nowrap">0</td><td nowrap="nowrap">0</td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td></tr><tr><td rowspan="1" colspan="2" nowrap="nowrap">沿海水果</td><td rowspan="1" colspan="1" nowrap="nowrap">海果（千克）</td><td nowrap="nowrap">0</td><td nowrap="nowrap">0</td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td></tr><tr><td rowspan="1" colspan="1" nowrap="nowrap">西部水果</td><td rowspan="1" colspan="1" nowrap="nowrap">瓜果</td><td rowspan="1" colspan="1" nowrap="nowrap">葡萄干（吨）</td><td nowrap="nowrap">0</td><td nowrap="nowrap">0</td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td></tr><tr><td rowspan="2" colspan="1" nowrap="nowrap">蔬菜产量</td><td rowspan="1" colspan="1" nowrap="nowrap">南方蔬菜</td><td rowspan="1" colspan="1" nowrap="nowrap">根类蔬菜</td><td rowspan="1" colspan="1" nowrap="nowrap">白萝卜（公斤）</td><td nowrap="nowrap">0</td><td nowrap="nowrap">0</td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td></tr><tr><td rowspan="1" colspan="1" nowrap="nowrap">北方蔬菜</td><td rowspan="1" colspan="1" nowrap="nowrap">叶类蔬菜</td><td rowspan="1" colspan="1" nowrap="nowrap">空心菜（千克）</td><td nowrap="nowrap">0</td><td nowrap="nowrap">0</td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td></tr>
  <tr><td rowspan="3" colspan="1" nowrap="nowrap">水果</td><td rowspan="1" colspan="1" nowrap="nowrap">南方水果</td><td rowspan="1" colspan="1" nowrap="nowrap">夏季水果</td><td rowspan="1" colspan="1" nowrap="nowrap">香蕉（千克）</td><td nowrap="nowrap">0</td><td nowrap="nowrap">0</td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td></tr><tr><td rowspan="1" colspan="2" nowrap="nowrap">沿海水果</td><td rowspan="1" colspan="1" nowrap="nowrap">海果（千克）</td><td nowrap="nowrap">0</td><td nowrap="nowrap">0</td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td></tr><tr><td rowspan="1" colspan="1" nowrap="nowrap">西部水果</td><td rowspan="1" colspan="1" nowrap="nowrap">瓜果</td><td rowspan="1" colspan="1" nowrap="nowrap">葡萄干（吨）</td><td nowrap="nowrap">0</td><td nowrap="nowrap">0</td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td></tr><tr><td rowspan="2" colspan="1" nowrap="nowrap">蔬菜产量</td><td rowspan="1" colspan="1" nowrap="nowrap">南方蔬菜</td><td rowspan="1" colspan="1" nowrap="nowrap">根类蔬菜</td><td rowspan="1" colspan="1" nowrap="nowrap">白萝卜（公斤）</td><td nowrap="nowrap">0</td><td nowrap="nowrap">0</td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td></tr><tr><td rowspan="1" colspan="1" nowrap="nowrap">北方蔬菜</td><td rowspan="1" colspan="1" nowrap="nowrap">叶类蔬菜</td><td rowspan="1" colspan="1" nowrap="nowrap">空心菜（千克）</td><td nowrap="nowrap">0</td><td nowrap="nowrap">0</td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td></tr>
  <tr><td rowspan="3" colspan="1" nowrap="nowrap">水果</td><td rowspan="1" colspan="1" nowrap="nowrap">南方水果</td><td rowspan="1" colspan="1" nowrap="nowrap">夏季水果</td><td rowspan="1" colspan="1" nowrap="nowrap">香蕉（千克）</td><td nowrap="nowrap">0</td><td nowrap="nowrap">0</td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td></tr><tr><td rowspan="1" colspan="2" nowrap="nowrap">沿海水果</td><td rowspan="1" colspan="1" nowrap="nowrap">海果（千克）</td><td nowrap="nowrap">0</td><td nowrap="nowrap">0</td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td></tr><tr><td rowspan="1" colspan="1" nowrap="nowrap">西部水果</td><td rowspan="1" colspan="1" nowrap="nowrap">瓜果</td><td rowspan="1" colspan="1" nowrap="nowrap">葡萄干（吨）</td><td nowrap="nowrap">0</td><td nowrap="nowrap">0</td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td></tr><tr><td rowspan="2" colspan="1" nowrap="nowrap">蔬菜产量</td><td rowspan="1" colspan="1" nowrap="nowrap">南方蔬菜</td><td rowspan="1" colspan="1" nowrap="nowrap">根类蔬菜</td><td rowspan="1" colspan="1" nowrap="nowrap">白萝卜（公斤）</td><td nowrap="nowrap">0</td><td nowrap="nowrap">0</td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td></tr><tr><td rowspan="1" colspan="1" nowrap="nowrap">北方蔬菜</td><td rowspan="1" colspan="1" nowrap="nowrap">叶类蔬菜</td><td rowspan="1" colspan="1" nowrap="nowrap">空心菜（千克）</td><td nowrap="nowrap">0</td><td nowrap="nowrap">0</td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td></tr>
  <tr><td rowspan="3" colspan="1" nowrap="nowrap">水果</td><td rowspan="1" colspan="1" nowrap="nowrap">南方水果</td><td rowspan="1" colspan="1" nowrap="nowrap">夏季水果</td><td rowspan="1" colspan="1" nowrap="nowrap">香蕉（千克）</td><td nowrap="nowrap">0</td><td nowrap="nowrap">0</td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td></tr><tr><td rowspan="1" colspan="2" nowrap="nowrap">沿海水果</td><td rowspan="1" colspan="1" nowrap="nowrap">海果（千克）</td><td nowrap="nowrap">0</td><td nowrap="nowrap">0</td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td></tr><tr><td rowspan="1" colspan="1" nowrap="nowrap">西部水果</td><td rowspan="1" colspan="1" nowrap="nowrap">瓜果</td><td rowspan="1" colspan="1" nowrap="nowrap">葡萄干（吨）</td><td nowrap="nowrap">0</td><td nowrap="nowrap">0</td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td></tr><tr><td rowspan="2" colspan="1" nowrap="nowrap">蔬菜产量</td><td rowspan="1" colspan="1" nowrap="nowrap">南方蔬菜</td><td rowspan="1" colspan="1" nowrap="nowrap">根类蔬菜</td><td rowspan="1" colspan="1" nowrap="nowrap">白萝卜（公斤）</td><td nowrap="nowrap">0</td><td nowrap="nowrap">0</td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td></tr><tr><td rowspan="1" colspan="1" nowrap="nowrap">北方蔬菜</td><td rowspan="1" colspan="1" nowrap="nowrap">叶类蔬菜</td><td rowspan="1" colspan="1" nowrap="nowrap">空心菜（千克）</td><td nowrap="nowrap">0</td><td nowrap="nowrap">0</td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td><td nowrap="nowrap"></td></tr>
</table>
</body>
</html>
